---
abstract: 'Interface to Ciseco Pi-Lite for Raspberry Pi'
author:
  - 'Jonathan Stowe <jns@gellyfish.co.uk>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Device-PiLite
provides:
  Device::PiLite:
    file: lib/Device/PiLite.pm
    version: '0.01'
requires:
  Device::SerialPort: '1.04'
  Moose: '2.1005'
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/jonathanstowe/Device-PiLite
version: '0.01'
